"""Build preference pairs (chosen/rejected) from rollout candidates."""

from __future__ import annotations

import argparse
import dataclasses
import logging
from collections import defaultdict
from pathlib import Path
from typing import Any

from sql_agent.utils import (
    read_jsonl,
    save_run_meta,
    setup_logging,
    timestamp,
    write_jsonl_line,
)


@dataclasses.dataclass
class PreferenceBuilderConfig:
    """Configuration for building preference pairs.

    Attributes:
        min_reward_gap: Minimum reward difference between chosen and
            rejected to form a valid pair.
        require_valid_sql: If ``True``, only candidates with
            ``valid=True`` are eligible.
        require_exec_ok: If ``True``, only candidates that executed
            successfully are eligible.
        allow_ties: If ``True``, pairs with ``gap == 0`` are included.
        max_pairs_per_example: Maximum number of pairs to emit per
            example group.
    """

    min_reward_gap: float = 0.3
    require_valid_sql: bool = True
    require_exec_ok: bool = False
    allow_ties: bool = False
    max_pairs_per_example: int = 1


@dataclasses.dataclass
class Stats:
    """Tracking statistics for preference building."""

    rollouts_read: int = 0
    examples_seen: int = 0
    examples_skipped_small_group: int = 0
    examples_skipped_gap: int = 0
    examples_skipped_no_valid: int = 0
    preferences_written: int = 0

    def to_dict(self) -> dict[str, Any]:
        """Converts the statistics into a dictionary."""
        return dataclasses.asdict(self)


def _parse_args() -> argparse.Namespace:
    """Parses CLI arguments."""
    parser = argparse.ArgumentParser(
        description="Build preference pairs from rollouts.jsonl"
    )

    parser.add_argument(
        "--rollouts_path",
        required=True,
        help="Path to rollouts.jsonl produced by collect_rollouts.py.",
    )
    parser.add_argument(
        "--output_dir",
        default="runs/preferences",
        help="Root directory where preferences run output will be written.",
    )
    parser.add_argument("--min_reward_gap", type=float, default=0.3)
    parser.add_argument(
        "--require_valid_sql", action="store_true", default=True
    )
    parser.add_argument(
        "--no_require_valid_sql",
        action="store_false",
        dest="require_valid_sql",
        help="If set, do not filter candidates by valid SQL.",
    )
    parser.add_argument(
        "--require_exec_ok", action="store_true", default=False
    )
    parser.add_argument("--allow_ties", action="store_true", default=False)
    parser.add_argument("--max_pairs_per_example", type=int, default=1)
    parser.add_argument(
        "--max_examples",
        type=int,
        default=None,
        help="Optional cap on the number of example groups to process.",
    )

    return parser.parse_args()


def _validate_args(args: argparse.Namespace) -> None:
    """Validates CLI arguments.

    Raises:
        ValueError: If any argument is out of range.
    """
    if args.min_reward_gap < 0:
        raise ValueError("--min_reward_gap must be >= 0")
    if args.max_pairs_per_example <= 0:
        raise ValueError("--max_pairs_per_example must be > 0")
    if args.max_examples is not None and args.max_examples <= 0:
        raise ValueError("--max_examples must be > 0 when provided")


def _group_key(row: dict[str, Any]) -> tuple[str, str, str]:
    """Returns a stable grouping key for a rollout row.

    Args:
        row: One rollout row.

    Returns:
        A ``(id, db_id, prompt)`` tuple.
    """
    return (
        str(row.get("id", "")),
        str(row.get("db_id", "")),
        str(row.get("prompt", "")),
    )


def _candidate_ok(
    row: dict[str, Any],
    cfg: PreferenceBuilderConfig,
) -> bool:
    """Checks if a candidate row should be eligible for preferences.

    Args:
        row: A dictionary containing candidate rollout data.
        cfg: Configuration object with filtering requirements.

    Returns:
        ``True`` if the row passes all configured filters.
    """
    if cfg.require_valid_sql and not row.get("valid", False):
        return False
    if cfg.require_exec_ok and not row.get("exec_ok", False):
        return False
    return True


def _ensure_im_end(sql: str) -> str:
    """Appends the ChatML end token if missing.

    Args:
        sql: The raw SQL string generated by the model.

    Returns:
        SQL string guaranteed to end with ``<|im_end|>``.
    """
    sql = (sql or "").strip()
    if not sql:
        return "<|im_end|>"
    if sql.endswith("<|im_end|>"):
        return sql
    return sql + "<|im_end|>"


def _pick_pairs_for_group(
    rows: list[dict[str, Any]],
    cfg: PreferenceBuilderConfig,
) -> list[tuple[dict[str, Any], dict[str, Any], float]]:
    """Selects (chosen, rejected) pairs for one example group.

    The chosen candidate is the one with the highest composite score.
    Rejected candidates are iterated from worst to best; the loop
    breaks early when the gap becomes too small because the gap can
    only shrink as we move toward better candidates.

    Args:
        rows: Candidate rollout rows for the same example.
        cfg: Builder configuration.

    Returns:
        List of ``(chosen_row, rejected_row, reward_gap)`` tuples.
    """
    eligible = [r for r in rows if _candidate_ok(r, cfg)]
    if len(eligible) < 2:
        return []

    def _sort_key(r: dict[str, Any]) -> tuple[float, int, int, int]:
        reward = float(r.get("reward", 0.0))
        exec_ok = 1 if r.get("exec_ok", False) else 0
        valid = 1 if r.get("valid", False) else 0
        cand_id = int(r.get("candidate_id", 0))
        return (reward, exec_ok, valid, -cand_id)

    eligible.sort(key=_sort_key, reverse=True)

    chosen = eligible[0]

    # Iterate from worst to best so gap only shrinks.
    rejected_pool = list(reversed(eligible))

    pairs: list[tuple[dict[str, Any], dict[str, Any], float]] = []

    for rejected in rejected_pool:
        if rejected is chosen:
            continue

        gap = float(chosen.get("reward", 0.0)) - float(
            rejected.get("reward", 0.0)
        )

        # Enforce min gap, but allow exact ties if configured.
        if gap < cfg.min_reward_gap:
            if not (cfg.allow_ties and gap == 0):
                break

        if not cfg.allow_ties and gap <= 0:
            continue

        pairs.append((chosen, rejected, gap))
        if len(pairs) >= cfg.max_pairs_per_example:
            break

    return pairs


def main() -> None:
    """Entry point for building preference pairs."""
    args = _parse_args()
    _validate_args(args)

    rollouts_path = Path(args.rollouts_path)
    if not rollouts_path.exists():
        raise FileNotFoundError(f"Rollouts file not found: {rollouts_path}")

    cfg = PreferenceBuilderConfig(
        min_reward_gap=float(args.min_reward_gap),
        require_valid_sql=bool(args.require_valid_sql),
        require_exec_ok=bool(args.require_exec_ok),
        allow_ties=bool(args.allow_ties),
        max_pairs_per_example=int(args.max_pairs_per_example),
    )

    run_dir = Path(args.output_dir) / f"preferences_{timestamp()}"
    setup_logging(run_dir, "build_preferences.log")
    logging.info("Run directory: %s", run_dir)
    logging.info("Reading rollouts: %s", rollouts_path)

    groups: defaultdict[tuple[str, str, str], list[dict[str, Any]]] = (
        defaultdict(list)
    )

    stats = Stats()
    for row in read_jsonl(rollouts_path):
        stats.rollouts_read += 1
        key = _group_key(row)
        if not key[0] or not key[1] or not key[2]:
            continue
        groups[key].append(row)

    logging.info(
        "Loaded %d rollout rows into %d groups.",
        stats.rollouts_read,
        len(groups),
    )

    prefs_path = run_dir / "preferences.jsonl"
    logging.info("Writing preferences to: %s", prefs_path)

    groups_items = sorted(groups.items(), key=lambda kv: kv[0][0])

    with prefs_path.open("w", encoding="utf-8") as out_fp:
        for group_idx, (key, rows) in enumerate(groups_items):
            if (
                args.max_examples is not None
                and stats.examples_seen >= args.max_examples
            ):
                break

            stats.examples_seen += 1
            if len(rows) < 2:
                stats.examples_skipped_small_group += 1
                continue

            pairs = _pick_pairs_for_group(rows, cfg)

            if not pairs:
                eligible = [r for r in rows if _candidate_ok(r, cfg)]
                if len(eligible) < 2:
                    stats.examples_skipped_no_valid += 1
                else:
                    stats.examples_skipped_gap += 1
                continue

            example_id, db_id, prompt = key

            for chosen_row, rejected_row, gap in pairs:
                pref = {
                    "id": example_id,
                    "db_id": db_id,
                    "prompt": prompt,
                    "chosen": _ensure_im_end(
                        str(chosen_row.get("candidate_sql", ""))
                    ),
                    "rejected": _ensure_im_end(
                        str(rejected_row.get("candidate_sql", ""))
                    ),
                    "meta": {
                        "chosen_reward": float(
                            chosen_row.get("reward", 0.0)
                        ),
                        "rejected_reward": float(
                            rejected_row.get("reward", 0.0)
                        ),
                        "reward_gap": float(gap),
                        "chosen_candidate_id": int(
                            chosen_row.get("candidate_id", 0)
                        ),
                        "rejected_candidate_id": int(
                            rejected_row.get("candidate_id", 0)
                        ),
                        "chosen_error_type": str(
                            chosen_row.get("error_type", "")
                        ),
                        "rejected_error_type": str(
                            rejected_row.get("error_type", "")
                        ),
                    },
                }
                write_jsonl_line(out_fp, pref)
                stats.preferences_written += 1

            if (group_idx + 1) % 200 == 0:
                logging.info(
                    "Progress: groups=%d/%d | examples_seen=%d | prefs=%d | "
                    "skipped_small=%d | skipped_gap=%d | skipped_no_valid=%d",
                    group_idx + 1,
                    len(groups_items),
                    stats.examples_seen,
                    stats.preferences_written,
                    stats.examples_skipped_small_group,
                    stats.examples_skipped_gap,
                    stats.examples_skipped_no_valid,
                )

    run_meta = {
        "timestamp": run_dir.name,
        "input_rollouts": rollouts_path.as_posix(),
        "output_preferences": prefs_path.as_posix(),
        "config": dataclasses.asdict(cfg),
        "stats": stats.to_dict(),
    }
    save_run_meta(run_dir, run_meta)

    logging.info(
        "Done. rollouts_read=%d | groups=%d | examples_seen=%d | "
        "prefs_written=%d | skipped_small=%d | skipped_gap=%d | "
        "skipped_no_valid=%d",
        stats.rollouts_read,
        len(groups),
        stats.examples_seen,
        stats.preferences_written,
        stats.examples_skipped_small_group,
        stats.examples_skipped_gap,
        stats.examples_skipped_no_valid,
    )
    logging.info("Preferences saved to: %s", prefs_path)


if __name__ == "__main__":
    main()
